name: phone_gun
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  shake: ^2.0.0
  audioplayers: ^0.20.1
  get: ^4.6.1
  camera: ^0.9.4+14
  permission_handler: ^9.1.0
  extended_image: ^6.0.1
  slide_to_confirm: ^1.1.0
  vibration: ^1.7.3

  # hive
  hive: ^2.0.5
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  hive_generator: ^1.1.1
  build_runner: ^2.1.7

flutter:

  uses-material-design: true

  assets:
    - assets/shot/
    - assets/reload/
    - assets/empty/
    - assets/image/

